/* Generated by :claw at 2019-10-24T20:07:44.594524Z */

#include "uv.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif


__CLAW_API uv_buf_t* __claw_uv_buf_init(uv_buf_t* arg0, char* arg1, unsigned int arg2) {
  uv_buf_t result = uv_buf_init(arg1, arg2);
 (*arg0) = result;
  return arg0;
}

#if defined(__cplusplus)
}
#endif
