image:
  - Visual Studio 2017

environment:
  global:
    NAME: uv
    ASDF_SYSTEM: bodge-uv
  matrix:
  - platform: x64
    configuration: Release
    TARGET_ARCH: x86_64
    PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool
  - platform: x86
    TARGET_ARCH: i686
    configuration: Release
    PATH: C:\msys64\mingw32\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-i686-toolchain mingw-w64-i686-libtool


skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

init:
  - git config --global core.autocrlf true

install:
  - git submodule update --init --recursive
  - pacman --needed --noconfirm -S zip unzip base-devel %PACKAGES%
  - curl -L http://bodge.borodust.org/files/install.sh | sh

build_script:
  - set APPVEYOR_BUILD_DIR=$(cygpath -m '%APPVEYOR_BUILD_FOLDER%')
  - set TARGET_ARTIFACT=lib%NAME%.dll.bodged-%TARGET_ARCH%-windows-%APPVEYOR_REPO_TAG_NAME%
  - set TARGET_SPEC=%TARGET_ARTIFACT%-spec.zip
  - >
    sh -c "
    MSYSTEM=MINGW64 . /etc/profile
    && export PATH=$HOME/.bodge/bin/:$PATH
    && cd %APPVEYOR_BUILD_DIR%/src/lib/
    && make clean build
    && ~/.bodge/bin/lisp regen-local-spec-and-zip
    --arch %TARGET_ARCH% \"%APPVEYOR_BUILD_DIR%\" %ASDF_SYSTEM%
    \"%APPVEYOR_BUILD_DIR%/%TARGET_SPEC%\""
  - mv %APPVEYOR_BUILD_FOLDER%\src\lib\lib%NAME%.dll.bodged %APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%

artifacts:
  - path: $(TARGET_ARTIFACT)
    name: target_artifact
  - path: $(TARGET_SPEC)
    name: target_spec

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact, target_spec
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
