image:
  - Visual Studio 2017

environment:
  global:
    NAME: uv
    ASDF_SYSTEM: bodge-uv
  matrix:
  - platform: x64
    configuration: Release
    SPEC_TARGET_ARCH: x86_64
    MSYS_PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\
  - platform: x86
    SPEC_TARGET_ARCH: i686
    configuration: Release
    MSYS_PATH: C:\msys64\mingw32\bin\;C:\msys64\usr\bin\

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

init:
  - git config --global core.autocrlf true

install:
  - git submodule update --init --recursive

build_script:
  - set TARGET_ARTIFACT=lib%NAME%.dll.bodged-%SPEC_TARGET_ARCH%-windows-%APPVEYOR_REPO_TAG_NAME%
  - set TARGET_SPEC=%TARGET_ARTIFACT%-spec.zip
  - cd src\lib\uv
  - vcbuild vs2017 %platform% release shared
  - mv Release\libuv.dll %APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%
  - set PATH=%MSYS_PATH%;%PATH%
  - set APPVEYOR_BUILD_DIR=$(cygpath -u '%APPVEYOR_BUILD_FOLDER%')
  - curl -L http://bodge.borodust.org/files/install.sh | sh
  - pacman --needed --noconfirm -S zip unzip base-devel
  - sh -c "~/.bodge/bin/lisp regen-local-spec-and-zip --arch %SPEC_TARGET_ARCH% \"$(cygpath -u '%APPVEYOR_BUILD_FOLDER%')\" %ASDF_SYSTEM% \"$(cygpath -u '%APPVEYOR_BUILD_FOLDER%\%TARGET_SPEC%')\""

artifacts:
  - path: $(TARGET_ARTIFACT)
    name: target_artifact
  - path: $(TARGET_SPEC)
    name: target_spec

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact, target_spec
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
